package lk.ijse.gdse.dao.util;

public enum DaoTypes {

    BRANCH,CHILD_ACCOUNT,CHILD_GUARDIAN,DEPOSIT_CHILD,DEPOSIT_LOAN_AMOUNT,DEPOSIT_TRANSACTION,INTER_ACCOUNT_TRANSACTION,LOAN,SAVINGS_ACCOUNT,WITHDRAWAL_MEMBER,WORKER


}
